<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_lahan_pertanian_model extends CI_Model
{

    public $table = 'tbl_lahan_pertanian';
    public $id = 'id_lahan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_lahan', $q);
	$this->db->or_like('luas_lahan', $q);
	$this->db->or_like('kk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_lahan', $q);
	$this->db->or_like('luas_lahan', $q);
	$this->db->or_like('kk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    public function data_lahan(){
		return $this->db->get('Tbl_lahan_pertanian');
		
	}

}

/* End of file Tbl_lahan_pertanian_model.php */
/* Location: ./application/models/Tbl_lahan_pertanian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-09-05 16:11:13 */
/* http://harviacode.com */